// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TP_Final.DataAccess;

#nullable disable

namespace TP_Final.Migrations
{
    [DbContext(typeof(PrestamosDbContext))]
    partial class PrestamosDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TP_Final.Domain.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreationDate = new DateTime(2023, 12, 27, 17, 50, 22, 849, DateTimeKind.Local).AddTicks(6905),
                            Description = "Libros"
                        },
                        new
                        {
                            Id = 2,
                            CreationDate = new DateTime(2023, 12, 27, 17, 50, 22, 849, DateTimeKind.Local).AddTicks(6922),
                            Description = "Indumentaria"
                        },
                        new
                        {
                            Id = 3,
                            CreationDate = new DateTime(2023, 12, 27, 17, 50, 22, 849, DateTimeKind.Local).AddTicks(6925),
                            Description = "Herramientas"
                        },
                        new
                        {
                            Id = 4,
                            CreationDate = new DateTime(2023, 12, 27, 17, 50, 22, 849, DateTimeKind.Local).AddTicks(6927),
                            Description = "Electronica"
                        },
                        new
                        {
                            Id = 5,
                            CreationDate = new DateTime(2023, 12, 27, 17, 50, 22, 849, DateTimeKind.Local).AddTicks(6929),
                            Description = "Objetos Varios"
                        });
                });

            modelBuilder.Entity("TP_Final.Domain.Loan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("DniPerson")
                        .HasColumnType("int");

                    b.Property<int>("IdThing")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReturnDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Loan");
                });

            modelBuilder.Entity("TP_Final.Domain.Person", b =>
                {
                    b.Property<int>("Dni")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Dni");

                    b.ToTable("Person");
                });

            modelBuilder.Entity("TP_Final.Domain.Thing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdCategory")
                        .HasColumnType("int");

                    b.Property<int>("PersonDni")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Thing");
                });
#pragma warning restore 612, 618
        }
    }
}
